import type { AnchorHTMLAttributes } from "react";
import { ArrowRight, Bot, CheckCircle2, CircleDollarSign, FileCheck2, LockKeyhole, ShieldCheck, Users } from "lucide-react";

function Link({ href, ...props }: AnchorHTMLAttributes<HTMLAnchorElement> & { href: string }) {
  return <a href={href} {...props} />;
}

const agents = [
  ["Finans Kontrol Ajanı", "Vade, borç, döviz etkisi ve tutarsız kayıtlar için finans ekibine inceleme notu hazırlar."],
  ["Proje Koordinasyon Ajanı", "Proje ilerlemesini, sorumluları, hedef tarihleri ve karar bekleyen konuları tek özette toplar."],
  ["Operasyon Takip Ajanı", "Tekrarlanan talepleri sınıflandırır, geciken işleri ayırır ve günlük takip listesini hazırlar."],
  ["Yönetim Raporlama Ajanı", "Doğrulanmış departman verilerinden kaynakları görülebilen bir yönetim özeti oluşturur."],
];

export default function AiServicePage() {
  return <main className="ai-service-page"><header className="article-header"><Link href="/"><img src="/assets/teksanor-logo.png" alt="Teksanor" /></Link><nav><Link href="/#cozumler">Çözümler</Link><Link href="/#yaklasim">Mühendislik</Link><Link href="/#icgoruler">İçgörüler</Link><Link href="/hakkimizda">Hakkımızda</Link></nav><Link className="article-portal-link" href="/giris">Portala gir <ArrowRight size={15} /></Link></header>
    <section className="ai-service-hero"><div><span>TEKSANOR OTONOM ÇALIŞMA KATMANI</span><h1>Ekibin yerine karar veren değil, ekibin dikkatini doğru işe taşıyan ajanlar.</h1><p>Biz, her departmana aynı sohbet ekranını yerleştirmiyoruz. Görevi, erişebileceği veri, duracağı nokta ve insan onayı baştan tanımlanmış çalışma profilleri kuruyoruz.</p><div><Link href="/giris?mode=register">Prototipi incele <ArrowRight size={17} /></Link><a href="#fiyatlandirma">Ücretlendirme modeline git</a></div></div><img src="/assets/teksanor-digital-twin.webp" alt="Teksanor veri ve yapay zekâ çalışma katmanı" /></section>
    <section className="ai-service-intro"><div><span>NEDEN BÖYLE TASARLIYORUZ?</span><h2>Bir ajanı “çalışan” gibi konumlandırıyorsak, görev tanımını da çalışan kadar açık yazıyoruz.</h2></div><p>Finans ajanının ödeme yapmasına, proje ajanının bütçeyi değiştirmesine veya operasyon ajanının tedarikçi adına sipariş vermesine izin vermiyoruz. Ajan bilgiyi toplar, karşılaştırır, taslak hazırlar ve sorumlu kişiye sunar. Kritik karar insanda kalır.</p></section>
    <section className="ai-agent-public-grid">{agents.map(([name, text], index) => <article key={name}><span>0{index + 1}</span><Bot size={25} /><h3>{name}</h3><p>{text}</p><div><CheckCircle2 size={15} /> İnsan onayıyla çalışır</div></article>)}</section>
    <section className="ai-how"><div><span>ÇALIŞMA MODELİ</span><h2>Önce iş akışını anlarız. Sonra ajanın nerede devreye gireceğini birlikte belirleriz.</h2></div><ol><li><Users /><span><b>Departmanı dinleriz</b>Günlük işi, tekrarları ve karar noktalarını ekipten öğreniriz.</span></li><li><FileCheck2 /><span><b>Görevi sınırlandırırız</b>Girdi, çıktı, veri kaynağı ve onay adımlarını yazılı hâle getiririz.</span></li><li><LockKeyhole /><span><b>Erişimi en aza indiririz</b>Ajan yalnızca görevini tamamlamak için gereken şirket verisine ulaşır.</span></li><li><ShieldCheck /><span><b>Kayıt ve kontrol ekleriz</b>Üretilen taslakları, insan onayını ve önemli aksiyonları izlenebilir tutarız.</span></li></ol></section>
    <section className="ai-pricing" id="fiyatlandirma"><div className="ai-pricing-title"><CircleDollarSign size={29} /><span>ŞEFFAF TİCARİ MODEL</span><h2>Müşteri tek bir toplam bedel görür; neye ödeme yaptığını bilir.</h2><p>ChatGPT aboneliği ile OpenAI API kullanımı aynı ürün değildir. Ajan entegrasyonunda API kullanımı ayrıca ölçülür. Model ve birim fiyatlar değişebildiği için satın alma ekranı, fatura dönemindeki güncel resmî OpenAI API fiyatlarını esas alır.</p></div><div className="ai-price-components"><article><span>01</span><h3>Kurulum ve süreç tasarımı</h3><p>Departman analizi, görev tanımı, güvenlik sınırları, test ve devreye alma.</p></article><article><span>02</span><h3>Aylık Teksanor hizmeti</h3><p>Portal, ajan yönetimi, izleme, bakım ve destek bedeli. Teksanor’un ticari kazancı bu açık hizmet kaleminde yer alır.</p></article><article><span>03</span><h3>Model kullanımı</h3><p>Onaylanan kullanım limiti içinde gerçekleşen OpenAI API tüketimi. Güncel birim fiyat için resmî kaynak esas alınır.</p><a href="https://openai.com/api/pricing/" target="_blank" rel="noreferrer">OpenAI fiyatlarını görüntüle <ArrowRight size={14} /></a></article><article><span>04</span><h3>Vergi ve ek hizmetler</h3><p>Uygulanabilen vergiler, özel entegrasyon veya ek depolama satın alma öncesinde ayrıca gösterilir.</p></article></div></section>
    <section className="ai-legal"><div><span>HUKUKİ VE OPERASYONEL ÇERÇEVE</span><h2>Gerçek kullanıma geçmeden önce açık rıza değil, doğru hukuki dayanak ve açık bilgilendirme gerekir.</h2></div><div><article><ShieldCheck /><h3>Veri işleme</h3><p>Hangi verinin, hangi amaçla, ne kadar süre işlendiği müşteriye açıklanır. Özel nitelikli veya gereksiz kişisel veri ajana gönderilmez.</p></article><article><LockKeyhole /><h3>Yetki ve sorumluluk</h3><p>Ajanın yapabileceği işlemler sözleşmede tanımlanır. Finansal, hukuki ve çalışan haklarını etkileyen kararlar yalnızca yetkili insan onayıyla sonuçlanır.</p></article><article><FileCheck2 /><h3>Satış öncesi bilgilendirme</h3><p>Hizmet kapsamı, toplam fiyat, yenileme, iptal, kullanım limiti ve üçüncü taraf altyapı bilgisi ödeme öncesinde gösterilir.</p></article></div><p className="ai-legal-warning">Bu sayfa ürün taslağını açıklar; hukuk danışmanlığı veya nihai sözleşme değildir. Teksanor’un resmî şirket bilgileri tamamlanmadan ücretli satış açılmaz. KVKK aydınlatma metni, hizmet sözleşmesi, veri işleme eki, gizlilik politikası ve ticari koşullar bir hukukçu tarafından şirket bilgileriyle son kez doğrulanmalıdır.</p></section>
    <footer className="article-footer"><img src="/assets/teksanor-logo.png" alt="Teksanor" /><span>Mühendislik aklı. Kontrollü yapay zekâ.</span><span>© 2026 Teksanor</span></footer></main>;
}
