import Link from "next/link";
import { ArrowRight, BarChart3, BrainCircuit, CheckCircle2, Cpu, Database, Settings2, ShieldCheck, Workflow } from "lucide-react";

const content = {
  cozumler: {
    kicker: "Çözüm portföyü", title: "İşletmeler için ölçülebilir teknoloji çözümleri.", text: "Dağınık verileri, manuel takip yükünü ve karar gecikmelerini azaltan sistemleri ihtiyaca göre tasarlarız.",
    cards: [["Finansal yönetim", "Borç, gider, nakit ve belgeleri tek görünümde izleyin."], ["Veri analitiği", "Excel ve operasyon verilerini anlaşılır göstergelere dönüştürün."], ["Süreç otomasyonu", "Tekrarlanan işleri kontrollü dijital akışlara taşıyın."], ["Kurumsal portal", "Her firma için ayrılmış güvenli çalışma alanı oluşturun."]],
    stats: [["4+", "Çözüm alanı"], ["%100", "Firma bazlı veri ayrımı"], ["7/24", "Erişilebilir portal"], ["TL", "Döviz ve altın takibi"]],
    detail: { heading: "Teksanor portalı ile neler yapabilirsiniz?", intro: "Portal; finans, proje ve organizasyon yönetimini tek güvenli çalışma alanında birleştirir.", items: [["Finansal takip", "Kredi kartı, KMH, yapılandırma ve elden borçları dönem dönem karşılaştırın; TCMB kurlarıyla döviz ve altın varlıklarınızın TL karşılığını görün."], ["Proje ve iş yönetimi", "Projeleri durum ve ilerleme yüzdesiyle izleyin; departman ve çalışan bazında iş takibi yapın."], ["Belge arşivi", "Dekont, Excel ve sözleşme gibi belgeleri firma alanınızda güvenle saklayın."], ["Ekip erişimi", "Rol temelli yetkilerle ekibinize kontrollü erişim tanımlayın."]] },
    faq: [["Portalı kullanmaya nasıl başlarım?", "Giriş sayfasından ücretsiz deneme hesabı oluşturabilir, firma bilgilerinizi tanımlayarak hemen kullanmaya başlayabilirsiniz."], ["Verilerim güvende mi?", "Her firmanın verisi kendi çalışma alanında ayrı tutulur; erişim rol temelli yetkilerle sınırlandırılır."], ["Excel dosyalarımı aktarabilir miyim?", "Evet. Mevcut Excel tablolarınızı panele aktararak kayıtlarınızı otomatik oluşturabilirsiniz."]],
  },
  muhendislik: {
    kicker: "Mühendislik yaklaşımı", title: "Problemi doğru tanımlayan, uygulanabilir sistemler.", text: "Teknoloji seçiminden süreç tasarımına kadar her adımı güvenlik, sürdürülebilirlik ve gerçek iş ihtiyacı üzerinden değerlendiririz.",
    cards: [["İhtiyaç analizi", "Mevcut süreci, veri kaynaklarını ve darboğazları belirleriz."], ["Sistem tasarımı", "Büyümeye uygun teknik ve operasyonel yapı kurarız."], ["Uygulama", "Çözümü küçük, ölçülebilir ve test edilebilir adımlarla hayata geçiririz."], ["Sürekli iyileştirme", "Kullanım verileriyle sistemi düzenli olarak geliştiririz."]],
    stats: [["4", "Aşamalı çalışma modeli"], ["Ölçülebilir", "Her adımda çıktı"], ["Test", "Devreye almadan önce"], ["Sürekli", "İyileştirme döngüsü"]],
    detail: { heading: "Mühendislik sürecimiz nasıl işler?", intro: "Her projeye aynı disiplinle yaklaşırız: önce anlamak, sonra tasarlamak, en son üretmek.", items: [["Keşif ve analiz", "Sahadaki gerçek süreci gözlemler, veri kaynaklarını ve manuel iş yükünü haritalarız."], ["Uygulanabilir tasarım", "Gösterişli değil; bakımı kolay, ölçeklenebilir ve maliyeti öngörülebilir mimariler kurarız."], ["Kademeli devreye alma", "Sistemleri küçük parçalar hâlinde, her adımı test ederek canlıya alırız."], ["Ölçüm ve geri bildirim", "Kullanım verilerini düzenli inceleyip sistemi iş ihtiyacına göre geliştiririz."]] },
    faq: [["Hangi tür projelerde çalışıyorsunuz?", "Veri takibi, süreç otomasyonu, kurumsal portal ve karar destek sistemleri başta olmak üzere işletme verimliliğine odaklı projelerde çalışırız."], ["Mevcut sistemlerimizle entegre olur mu?", "Analiz aşamasında mevcut araçlarınızı inceler, entegrasyon ihtiyacını tasarımın parçası hâline getiririz."], ["Proje süresi nasıl belirlenir?", "Kapsam netleştikten sonra işi ölçülebilir adımlara böler, her adım için ayrı takvim veririz."]],
  },
  yapayzeka: {
    kicker: "Yapay zekâ ve veri", title: "İnsan kontrolünü koruyan yapay zekâ çözümleri.", text: "Yapay zekâyı gösteriş için değil; bilgiye daha hızlı ulaşmak, tekrarları azaltmak ve karar kalitesini yükseltmek için kullanırız.",
    cards: [["Akıllı analiz", "Veri içindeki eğilimleri ve dikkat gerektiren alanları görünür kılın."], ["Belge işleme", "Dağınık belgeleri ve tabloları düzenli kayıtlara dönüştürün."], ["Karar desteği", "Açıklanabilir göstergelerle yöneticilerin karar sürecini güçlendirin."], ["Kontrollü otomasyon", "Kritik işlemlerde insan onayını ve izlenebilirliği koruyun."]],
    stats: [["İnsan", "Onayı her kritik adımda"], ["Açıklanabilir", "Göstergeler ve sonuçlar"], ["İzlenebilir", "Tüm otomatik işlemler"], ["Veri", "Odaklı karar desteği"]],
    detail: { heading: "Yapay zekâyı nerede ve nasıl kullanıyoruz?", intro: "Amacımız insanın yerini almak değil; yöneticinin bilgiye ulaşma ve karar verme hızını artırmak.", items: [["Eğilim ve anomali tespiti", "Finansal ve operasyonel verilerdeki değişimleri erken fark etmenizi sağlarız."], ["Belge ve tablo işleme", "Excel, PDF ve dağınık kayıtları yapılandırılmış veriye dönüştürürüz."], ["Karar destek göstergeleri", "Sonuçları nedenleriyle birlikte, anlaşılır göstergelerle sunarız."], ["Onaylı otomasyon", "Otomatik akışlarda kritik adımlar her zaman insan onayına bağlanır."]] },
    faq: [["Yapay zekâ kararları kendi başına mı alıyor?", "Hayır. Kritik işlemler her zaman insan onayından geçer; sistem öneri ve gösterge sunar."], ["Verilerimiz model eğitiminde kullanılıyor mu?", "Firma verileriniz kendi çalışma alanınızda kalır; izniniz olmadan başka amaçla kullanılmaz."], ["Küçük işletmeler için de uygun mu?", "Evet. Çözümler ihtiyaca göre ölçeklenir; küçük ekipler için sade başlangıç kurulumları sunarız."]],
  },
  hakkimizda: {
    kicker: "Teksanor hakkında", title: "Mühendislik disipliniyle geliştirilen teknoloji markası.", text: "Teksanor; işletmelerin süreçlerini daha anlaşılır, izlenebilir ve verimli hâle getirmeyi amaçlayan mühendislik, veri ve yapay zekâ odaklı bir teknoloji girişimidir.",
    cards: [["Misyon", "Karmaşık teknolojileri işletmeler için sade ve uygulanabilir hâle getirmek."], ["Çalışma ilkesi", "Doğrulanabilir bilgi, ölçülebilir sonuç ve açık iletişim."], ["Güvenlik", "Firma bazlı veri ayrımı ve rol temelli erişim yaklaşımı."], ["Gelişim", "İhtiyaca göre büyüyen, sürdürülebilir ürünler tasarlamak."]],
    stats: [["3", "Odak alanı: mühendislik, veri, yapay zekâ"], ["Sade", "Uygulanabilir çözümler"], ["Açık", "İletişim ve raporlama"], ["Güven", "Rol temelli erişim"]],
    detail: { heading: "Teksanor'u farklı kılan nedir?", intro: "Teknolojiyi amacına uygun kullanan, ölçülebilir sonuç odaklı bir ekip kültürüyle çalışırız.", items: [["Gerçek ihtiyaç odağı", "Projeye teknolojiden değil, işletmenin gerçek probleminden başlarız."], ["Sade ve dürüst iletişim", "Teknik kararları anlaşılır dille açıklar, doğrulanamayan vaatlerde bulunmayız."], ["Güvenlik önceliği", "Veri ayrımı, yetkilendirme ve izlenebilirlik her ürünün temelidir."], ["Uzun vadeli ortaklık", "Sistemi devreye aldıktan sonra da ölçer, bakımını yapar ve geliştiririz."]] },
    faq: [["Teksanor hangi sektörlere hizmet veriyor?", "Ölçeği fark etmeksizin süreçlerini dijitalleştirmek isteyen üretim, hizmet ve ticaret işletmelerine hizmet veriyoruz."], ["Sizinle nasıl iletişime geçebilirim?", "Portala giriş sayfasından deneme hesabı oluşturabilir veya kurumsal iletişim kanallarımızdan bize ulaşabilirsiniz."], ["Ürünleriniz sürekli gelişiyor mu?", "Evet. Kullanıcı geri bildirimleri ve kullanım verileriyle ürünlerimizi düzenli olarak güncelliyoruz."]],
  },
} as const;

export default function CorporatePage({ type }: { type: keyof typeof content }) {
  const page = content[type];
  const icons = [BarChart3, Database, Workflow, ShieldCheck];
  return <main className="corporate-page">
    <header className="corporate-header"><Link href="/"><img src="/assets/teksanor-logo.png" alt="Teksanor" /></Link><nav><Link href="/cozumler">Çözümler</Link><Link href="/muhendislik">Mühendislik</Link><Link href="/yapay-zeka">Yapay Zekâ</Link><Link href="/hakkimizda">Hakkımızda</Link></nav><Link className="corporate-login" href="/giris">Portala giriş <ArrowRight size={16} /></Link></header>
    <section className="corporate-hero"><img src="/assets/teksanor-engineering-lab.webp" alt="Teksanor mühendislik ve akıllı üretim laboratuvarı" /><div><span>{page.kicker}</span><h1>{page.title}</h1><p>{page.text}</p><Link href="/giris?mode=register">Ücretsiz deneyin <ArrowRight size={17} /></Link></div></section>
    <section className="corporate-stats">{page.stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
    <section className="corporate-values">{page.cards.map(([title, text], index) => { const Icon = icons[index]; return <article key={title}><Icon size={24} /><span>0{index + 1}</span><h2>{title}</h2><p>{text}</p></article>; })}</section>
    <section className="corporate-detail"><div className="corporate-detail-head"><span>{page.kicker}</span><h2>{page.detail.heading}</h2><p>{page.detail.intro}</p></div><div className="corporate-detail-grid">{page.detail.items.map(([title, text]) => <article key={title}><CheckCircle2 size={20} /><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="corporate-process"><div><span>Teksanor çalışma modeli</span><h2>Analizden çalışan sisteme, kontrollü ilerleme.</h2></div><ol><li><CheckCircle2 />İhtiyacı ve hedefi netleştir</li><li><Settings2 />Uygulanabilir sistemi tasarla</li><li><Cpu />Test ederek devreye al</li><li><BrainCircuit />Veriyle sürekli geliştir</li></ol></section>
    <section className="corporate-faq"><div className="corporate-detail-head"><span>Merak edilenler</span><h2>Sık sorulan sorular</h2></div><div className="corporate-faq-list">{page.faq.map(([question, answer]) => <details key={question}><summary>{question}<ArrowRight size={16} /></summary><p>{answer}</p></details>)}</div></section>
    <section className="corporate-cta"><div><h2>Teksanor ile tanışın</h2><p>Ücretsiz deneme hesabı oluşturun; finans, proje ve ekip yönetimini tek portalda deneyimleyin.</p></div><Link href="/giris?mode=register">Ücretsiz deneyin <ArrowRight size={17} /></Link></section>
    <footer className="corporate-footer"><img src="/assets/teksanor-logo.png" alt="Teksanor" /><span>© 2026 Teksanor · Mühendislik, veri ve yapay zekâ</span></footer>
  </main>;
}
