import Link from "next/link";
import {
  ArrowRight, BarChart3, Boxes, Building2, CalendarClock, CheckCircle2, ClipboardCheck,
  CloudCog, Database, FileCheck2, Gauge, HardHat, KeyRound, Layers3, LockKeyhole,
  Network, PackageCheck, Route, ShieldCheck, Smartphone, Wrench,
} from "lucide-react";
import { PublicPage } from "./PublicShell";

export const sectors = [
  { slug: "teknik-servis", icon: Wrench, title: "Teknik servis", summary: "Talep, iş emri, saha ziyareti, servis kanıtı ve kapanış sürecini tek akışta yönetin.", metrics: ["İş emri önceliği", "Teknisyen planı", "Servis geçmişi"] },
  { slug: "bakim-onarim", icon: CalendarClock, title: "Bakım ve onarım", summary: "Periyodik bakım planlarını, ekipman geçmişini ve geciken işleri görünür kılın.", metrics: ["Bakım takvimi", "Arıza kaydı", "Ekipman geçmişi"] },
  { slug: "muhendislik-taahhut", icon: HardHat, title: "Mühendislik ve taahhüt", summary: "Proje bütçesi, saha ilerlemesi, satın alma ve teslimatları aynı yönetim görünümünde birleştirin.", metrics: ["Proje kilometre taşı", "Bütçe takibi", "Saha teslimi"] },
] as const;

const modules = [
  ["Proje ve görev", "Kapsam, sorumlu, termin, bütçe ve ilerlemeyi aynı kayıtta tutar.", Route],
  ["İş emri ve saha", "Planlamadan saha kanıtına ve kapanışa kadar servis döngüsünü izler.", Wrench],
  ["Finansal görünüm", "Ödeme, borç, gider, nakit, döviz ve altın karşılıklarını yönetim özeti hâline getirir.", BarChart3],
  ["Satın alma", "Talep, onay, tedarikçi, sipariş ve teslimat adımlarını görünür kılar.", PackageCheck],
  ["Belge merkezi", "Dekont, sözleşme, fotoğraf ve teknik dokümanları firma alanında toplar.", FileCheck2],
  ["Risk ve kalite", "Riskleri, etkilerini, sorumluları ve iyileştirme adımlarını kayda alır.", ClipboardCheck],
] as const;

export function PlatformPage() {
  return <PublicPage>
    <section className="enterprise-hero enterprise-hero-split">
      <div><span className="enterprise-kicker">Teksanor operasyon platformu</span><h1>Sahadaki işi, merkezdeki karara bağlayan tek çalışma alanı.</h1><p>Excel, mesaj, dekont ve kişisel notlara dağılan operasyon verisini; yetkili kişilerin kullandığı, kayıtların izlenebildiği ve yöneticinin gerçek durumu görebildiği bir sisteme dönüştürür.</p><div className="enterprise-cta-row"><Link className="enterprise-primary" href="/pilot">Pilot kapsamını incele <ArrowRight size={17}/></Link><Link className="enterprise-secondary" href="/giris">Çalışma alanını aç</Link></div></div>
      <div className="enterprise-image-card"><img src="/assets/teksanor-field-operations.svg" alt="Teksanor saha operasyonu ve mühendislik ekibi" /><span>OPERASYON · SAHA · YÖNETİM</span></div>
    </section>
    <section className="enterprise-section"><div className="enterprise-heading"><span>Modüler omurga</span><h2>Günlük işin tamamını tek ekrana sıkıştırmadan, birbirine bağlı modüllerle yönetin.</h2><p>Her ekip kendi ekranında çalışır; yönetim özeti yalnızca karar için gerekli bilgiyi toplar.</p></div><div className="module-map">{modules.map(([title,text,Icon],i)=><article key={title}><em>0{i+1}</em><Icon size={25}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="enterprise-dark-section">
      <div><span className="enterprise-kicker">İş akışı</span><h2>Kayıt açılır, sorumlu atanır, kanıt eklenir, sonuç kapanır.</h2><p>Teksanor’un değeri yalnızca veri saklamak değildir. Her kaydın bir sahibi, durumu, tarihi ve izlenebilir sonucu olur.</p></div>
      <div className="workflow-diagram">{["Talep","Planlama","Saha uygulaması","Kontrol","Kapanış"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span>{i<4&&<ArrowRight size={18}/>}</div>)}</div>
    </section>
    <section className="enterprise-section"><div className="enterprise-heading"><span>Yönetim göstergeleri</span><h2>Güzel grafik değil, karar aldıran görünürlük.</h2></div><div className="chart-story"><div className="css-bars" aria-label="Örnek operasyon görünürlüğü grafiği"><i style={{height:"72%"}}/><i style={{height:"48%"}}/><i style={{height:"86%"}}/><i style={{height:"64%"}}/><i style={{height:"92%"}}/><i style={{height:"78%"}}/></div><div><h3>Yönetici neyi görür?</h3><ul><li><CheckCircle2/> Açık ve geciken işlerin dağılımı</li><li><CheckCircle2/> Proje bütçesi ve gerçekleşen gider</li><li><CheckCircle2/> Yaklaşan ödeme ve bakım tarihleri</li><li><CheckCircle2/> Departman, sorumlu ve durum bazlı yük</li></ul><small>Gösterilen grafik örnek arayüz anlatımıdır; müşteri başarısı veya gerçek performans verisi değildir.</small></div></div></section>
  </PublicPage>;
}

export function SectorsPage() {
  return <PublicPage><section className="enterprise-hero center"><span className="enterprise-kicker">Dikey çözümler</span><h1>Herkese aynı panel değil; işin doğasına göre düzenlenmiş süreçler.</h1><p>İlk ürün odağımız teknik servis, bakım-onarım ve mühendislik saha firmalarıdır. Her sektör sayfası görev akışını, temel kayıtlarını ve ölçüm noktalarını açıkça gösterir.</p></section><section className="sector-grid">{sectors.map(({slug,icon:Icon,title,summary,metrics})=><Link href={`/sektorler/${slug}`} key={slug}><Icon size={29}/><h2>{title}</h2><p>{summary}</p><ul>{metrics.map(x=><li key={x}><CheckCircle2 size={15}/>{x}</li>)}</ul><span>Çözümü incele <ArrowRight size={16}/></span></Link>)}</section></PublicPage>;
}

const sectorDetails: Record<string, {title:string; lead:string; image:string; flow:string[]; records:string[]; kpis:string[]}> = {
  "teknik-servis": {title:"Teknik servis operasyonunu ilk talepten imzalı kapanışa kadar yönetin.",lead:"Müşteri talebini kaybeden, teknisyen planını mesajla yapan ve servis geçmişini dosyalarda arayan ekipler için ortak çalışma düzeni.",image:"/assets/teksanor-field-operations.svg",flow:["Talep ve öncelik","Teknisyen atama","Saha ziyareti","Fotoğraf ve not","Müşteri sonucu"],records:["Müşteri ve lokasyon","Cihaz veya ekipman","Arıza tanımı","Kullanılan parça","Çalışma süresi","Servis sonucu"],kpis:["İlk yanıt süresi","Açık iş emri","Tekrar arıza","Zamanında kapanış"]},
  "bakim-onarim": {title:"Bakım takvimini ekipman geçmişiyle birlikte yönetin.",lead:"Periyodik bakımın unutulmasını, arıza bilgisinin kişide kalmasını ve aynı ekipmana tekrar tekrar kontrolsüz müdahale edilmesini önleyen yapı.",image:"/assets/teksanor-engineering-lab.webp",flow:["Ekipman kaydı","Bakım planı","Hatırlatma","Kontrol listesi","Geçmiş ve sonraki tarih"],records:["Ekipman kodu","Konum ve sorumlu","Bakım sıklığı","Kontrol listesi","Arıza ve parça","Sonraki bakım"],kpis:["Geciken bakım","Arıza sıklığı","Planlı/plansız oranı","Ekipman duruşu"]},
  "muhendislik-taahhut": {title:"Proje, saha, satın alma ve bütçeyi aynı ilerleme hikâyesinde birleştirin.",lead:"Proje yöneticisi, saha ekibi ve satın alma arasındaki bilgi kopukluğunu azaltan; kilometre taşı ve teslimat kanıtını görünür kılan çalışma alanı.",image:"/assets/teksanor-digital-twin.webp",flow:["Kapsam ve bütçe","İş paketi","Satın alma","Saha ilerlemesi","Hakediş ve teslim"],records:["Proje kodu","Bütçe kalemi","Kilometre taşı","Teknik belge","Tedarik talebi","Teslim kanıtı"],kpis:["Bütçe sapması","Termin sapması","Açık satın alma","Tamamlanma yüzdesi"]},
};

export function SectorDetailPage({slug}:{slug:string}) {
  const d=sectorDetails[slug]||sectorDetails["teknik-servis"];
  return <PublicPage><section className="enterprise-hero enterprise-hero-split"><div><span className="enterprise-kicker">Sektörel çözüm</span><h1>{d.title}</h1><p>{d.lead}</p><Link className="enterprise-primary" href="/pilot">Pilot kapsamı oluştur <ArrowRight size={17}/></Link></div><div className="enterprise-image-card"><img src={d.image} alt={d.title}/></div></section><section className="enterprise-section"><div className="enterprise-heading"><span>Standart çalışma döngüsü</span><h2>Her adımın sahibi, zamanı ve kanıtı belli olur.</h2></div><div className="workflow-diagram light">{d.flow.map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span>{i<d.flow.length-1&&<ArrowRight size={18}/>}</div>)}</div></section><section className="two-table-section"><article><h2>Tutulan temel kayıtlar</h2><table><tbody>{d.records.map((x,i)=><tr key={x}><th>0{i+1}</th><td>{x}</td></tr>)}</tbody></table></article><article><h2>İzlenen göstergeler</h2><table><tbody>{d.kpis.map((x,i)=><tr key={x}><th><Gauge size={17}/></th><td>{x}</td></tr>)}</tbody></table></article></section><section className="legal-context-note"><ShieldCheck/><div><b>Operasyon kaydı ve karar desteği</b><p>Teksanor bu akışlarda operasyonel kayıt tutar ve yönetim görünürlüğü sağlar. Resmî muhasebe, mevzuat beyanı, iş güvenliği yetkilendirmesi veya teknik uygunluk belgesi yerine geçmez.</p></div></section></PublicPage>;
}

export function IntegrationsPage() {
 const rows=[["Excel içe/dışa aktarma","Mevcut tabloları kontrollü olarak taşımak ve rapor almak","Çalışıyor"],["TCMB döviz kurları","Dövizli kayıtların TL karşılığını resmî günlük göstergeyle hesaplamak","Çalışıyor"],["Cloudflare D1 ve R2","Yapısal kayıt ve firma belgelerini uygulama katmanında saklamak","Çalışıyor"],["Muhasebe/ERP API","Onaylı entegrasyonla çift kayıt yükünü azaltmak","Planlı"],["E-posta ve takvim","Hatırlatma ve görev tarihlerini dış sistemlerle eşlemek","Planlı"],["Telegram/mesajlaşma","Yetkili bildirimleri güvenli aracı servisle iletmek","Değerlendirme"]];
 return <PublicPage><section className="enterprise-hero center"><span className="enterprise-kicker">Entegrasyon yaklaşımı</span><h1>Veriyi kopyalayan değil, kayıt kaynağını belli tutan bağlantılar.</h1><p>Her bağlantı için erişim kapsamı, veri yönü, sorumluluk ve kesinti davranışı tanımlanır. Çalışmayan bağlantıyı hazırmış gibi göstermiyoruz.</p></section><section className="integration-architecture"><div><Database/><b>Teksanor veri katmanı</b><small>Firma bazlı operasyon kayıtları</small></div><Network/><div><CloudCog/><b>Onaylı bağlantılar</b><small>Dosya, kur, API ve bildirim</small></div><Network/><div><Boxes/><b>İş sistemleri</b><small>Muhasebe, ERP, takvim</small></div></section><section className="enterprise-table-wrap"><table className="enterprise-table"><thead><tr><th>Bağlantı</th><th>İş amacı</th><th>Durum</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td><span className={`status-pill ${r[2]==="Çalışıyor"?"live":"planned"}`}>{r[2]}</span></td></tr>)}</tbody></table></section></PublicPage>;
}

export function TrustPage() {
 const controls=[["Firma ayrımı","Operasyon kayıtlarında firma kimliğiyle sorgu sınırı ve üyelik kontrolü","Uygulamada"],["Rol tabanlı erişim","Yönetici ve kullanıcı işlemlerinin ayrılması","Uygulamada"],["Güvenli oturum","HttpOnly, Secure ve SameSite oturum çerezi","Uygulamada"],["Dosya kontrolü","Tür, boyut ve yükleme doğrulamaları","Temel düzey"],["Yönetici MFA","İkinci doğrulama adımı","Pilot öncesi"],["E-posta doğrulama ve kurtarma","Hesap sahipliği ve güvenli parola yenileme","Pilot öncesi"],["Kötücül dosya taraması","Karantina ve içerik taraması","Pilot öncesi"],["Geri yükleme tatbikatı","D1/R2 yedeğinin ölçülmüş geri dönüşü","Pilot öncesi"]];
 return <PublicPage><section className="enterprise-hero enterprise-hero-split"><div><span className="enterprise-kicker">Güven merkezi</span><h1>Güvenlik, pazarlama sözü değil; kontrol, kanıt ve açık durum bilgisidir.</h1><p>Verinin nerede işlendiğini, kimin erişebildiğini ve hangi kontrollerin henüz tamamlanmadığını açıkça gösteriyoruz.</p><Link className="enterprise-secondary" href="/kurumsal-durum">Açık ürün durumunu gör</Link></div><div className="enterprise-image-card"><img src="/assets/teksanor-trust-architecture.svg" alt="Teksanor güvenli veri mimarisi"/></div></section><section className="enterprise-table-wrap"><table className="enterprise-table"><thead><tr><th>Kontrol</th><th>Uygulama</th><th>Durum</th></tr></thead><tbody>{controls.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td><span className={`status-pill ${r[2]==="Uygulamada"?"live":r[2]==="Temel düzey"?"partial":"planned"}`}>{r[2]}</span></td></tr>)}</tbody></table></section><section className="enterprise-section" id="hukuki"><div className="enterprise-heading"><span>Hukuki çerçeve</span><h2>Üretim kullanımı, veri envanteri ve sözleşmeli sorumlulukla başlar.</h2></div><div className="legal-grid"><article><LockKeyhole/><h3>Veri işleme</h3><p>Müşteri firma veri sorumlusu; Teksanor’un rolü, işlenen veri ve alt hizmet sağlayıcılar sözleşmede açıkça tanımlanır.</p></article><article><FileCheck2/><h3>Saklama ve silme</h3><p>Kayıt türüne göre saklama süreleri belirlenir; gereksiz veri tutulmaz ve silme talepleri kayıt altına alınır.</p></article><article><KeyRound/><h3>Erişim ve denetim</h3><p>En az yetki ilkesi, işlem geçmişi ve hesap kapatma akışları şirket politikasıyla birlikte uygulanır.</p></article><article><ShieldCheck/><h3>Finansal sınır</h3><p>Kur ve altın değerleri bilgilendirme/hesaplama referansıdır; yatırım tavsiyesi, resmî muhasebe kaydı veya bağlayıcı fiyat değildir.</p></article></div><p className="legal-disclaimer">Bu sayfa genel ürün yaklaşımını açıklar; müşteriye özgü KVKK, ticaret, iş hukuku ve sektör yükümlülükleri için sözleşme öncesi veri envanteri ve hukuki kapsam çalışması yapılır.</p></section></PublicPage>;
}

export function PilotPage() {
 const phases=[["01","Keşif","İş akışı, kullanıcılar, veri kaynakları ve başarı ölçüsü belirlenir."],["02","Kurulum","Sınırlı modüller, roller ve örnek verilerle çalışma alanı hazırlanır."],["03","Gerçek kullanım","6–12 hafta boyunca seçili ekip ve süreçlerde kayıt tutulur."],["04","Sonuç","Kazanılan zaman, kayıt kalitesi, gecikme ve kullanıcı kabulü ölçülür."]];
 return <PublicPage><section className="enterprise-hero center"><span className="enterprise-kicker">Kontrollü ücretli pilot</span><h1>Büyük sözleşmeden önce, gerçek işte kanıtlanan küçük kapsam.</h1><p>Pilotun amacı bütün şirketi bir gecede dönüştürmek değil; seçilen bir iş akışında Teksanor’un ölçülebilir değer üretip üretmediğini göstermek.</p></section><section className="pilot-timeline">{phases.map(([n,t,x])=><article key={n}><b>{n}</b><h2>{t}</h2><p>{x}</p></article>)}</section><section className="two-table-section"><article><h2>Pilotta ölçülecekler</h2><table><tbody>{["Excel/mesaj dışına taşınan kayıt","Yöneticinin rapor hazırlama süresi","Geciken iş ve ödeme görünürlüğü","Saha kanıtı tamamlama oranı","Kullanıcıların düzenli kullanım oranı"].map(x=><tr key={x}><th><Gauge size={17}/></th><td>{x}</td></tr>)}</tbody></table></article><article><h2>Pilot kapsamına girmez</h2><table><tbody>{["Resmî muhasebe yerine geçme","Kontrolsüz yapay zekâ kararı","Sınırsız özel geliştirme","İzinsiz veri aktarımı","Kanıtlanmamış başarı garantisi"].map(x=><tr key={x}><th>—</th><td>{x}</td></tr>)}</tbody></table></article></section></PublicPage>;
}

export function PricingPage() {
 const plans=[{name:"Pilot",lead:"Tek süreçte kanıt",items:["6–12 haftalık sınırlı kapsam","Kurulum ve veri şablonu","Ekip eğitimi","Başarı ölçümü"],cta:"Pilot görüşmesi"},{name:"Operasyon",lead:"Günlük şirket kullanımı",items:["Proje, saha ve finans modülleri","Rol ve firma çalışma alanı","Belge ve rapor merkezi","Standart destek"],cta:"Kapsam belirle"},{name:"Kurumsal",lead:"Özel yönetim ve entegrasyon",items:["Gelişmiş yetki ve denetim","Özel rapor ve iş akışı","Entegrasyon paketi","SLA ve geçiş planı"],cta:"Teklif iste"}];
 return <PublicPage><section className="enterprise-hero center"><span className="enterprise-kicker">Şeffaf kapsamlandırma</span><h1>Fiyat, kullanıcı sayısından önce çözülen işin kapsamına göre belirlenir.</h1><p>Kurulum, veri taşıma, eğitim, modül, entegrasyon ve destek ayrı kalemler hâlinde teklif edilir. Gizli komisyon veya finans kaydı üzerinden işlem payı alınmaz.</p></section><section className="pricing-grid">{plans.map((p,i)=><article className={i===1?"featured":""} key={p.name}><span>{i===1?"Önerilen başlangıç":"Paket"}</span><h2>{p.name}</h2><p>{p.lead}</p><ul>{p.items.map(x=><li key={x}><CheckCircle2 size={16}/>{x}</li>)}</ul><Link href="/pilot">{p.cta}<ArrowRight size={16}/></Link></article>)}</section><section className="legal-context-note"><ShieldCheck/><div><b>Ödeme öncesi açık bilgi</b><p>Toplam ücret, yenileme, iptal, kullanım sınırı, üçüncü taraf altyapı ve ek hizmetler teklif ve sözleşmede ödeme öncesi gösterilir.</p></div></section></PublicPage>;
}

export function HelpPage() {
 const faq=[["Teksanor resmî muhasebe programı mı?","Hayır. Operasyonel finans görünürlüğü ve karar desteği sağlar; resmî defter, beyan ve e-fatura süreçlerinin yerine geçmez."],["Firma verileri birbirinden ayrılıyor mu?","API sorguları firma kimliği ve üyelik bağlamıyla sınırlandırılır. Kurumsal pilot öncesi bu ayrım otomatik testlerle ayrıca kanıtlanacaktır."],["Döviz ve altın değerleri ne için kullanılır?","Dövizli ve altın cinsinden kayıtların TL karşılığını göstermek için referans hesaplamada kullanılır; bağlayıcı işlem fiyatı değildir."],["Excel kayıtları taşınabilir mi?","Desteklenen şablonlarla içe aktarma ve rapor dışa aktarma akışları bulunur. Aktarım öncesi sütun ve para biçimi kontrol edilir."],["Yapay zekâ kendi başına karar verir mi?","Hayır. Ajan katmanı prototip ve öneri modundadır; finansal, hukuki veya çalışanı etkileyen kritik sonuçlar otomatik bağlanmaz."],["Pilot neden ücretli?","Gerçek kullanıcı, gerçek veri hazırlığı, eğitim ve ölçüm gerektirir. Ücretli pilot iki tarafın da sınırları belirlenmiş ciddi bir çalışma yürütmesini sağlar."]];
 return <PublicPage><section className="enterprise-hero center"><span className="enterprise-kicker">Yardım merkezi</span><h1>Ürünü kullanmadan önce bilinmesi gerekenler.</h1><p>Hızlı cevaplar, çalışma sınırları ve doğru başlangıç adımları.</p></section><section className="faq-grid">{faq.map(([q,a])=><details key={q}><summary>{q}<ArrowRight size={18}/></summary><p>{a}</p></details>)}</section><section className="help-paths"><Link href="/platform"><Layers3/><b>Platform rehberi</b><span>Modülleri ve iş akışını incele</span></Link><Link href="/guven"><ShieldCheck/><b>Güven merkezi</b><span>Kontrolleri ve açık işleri gör</span></Link><Link href="/pilot"><ClipboardCheck/><b>Pilot başlangıcı</b><span>Kapsamı ve ölçümü planla</span></Link></section></PublicPage>;
}

