"use client";
import Link from "next/link";
import {useEffect,useState,useRef,type FormEvent} from "react";
import "./service.css";
type Job={id:string;version:number;title:string;description:string;customer_name:string;location:string;order_number:string;scheduled_date:string;stage:string;outcome:string;quote_cents:number;labor_cents?:number;parts_cents?:number;travel_cents?:number;paid_cents?:number;margin_cents?:number;remaining_cents?:number;asset_id?:string;asset_code?:string;asset_name?:string};
type Data={jobs:Job[];assets:{id:string;name:string;asset_code:string}[];members:{id:string;full_name:string}[];manage:boolean;canWrite:boolean;userId:string;organization:{id:string;name:string}};
const labels:Record<string,string>={requested:"Talep",quoted:"Teklif bekliyor",quote_approved:"Teklif onaylandı",in_progress:"İş sürüyor",completed:"İş onayı bekliyor",accepted:"İş onaylandı",collected:"Tahsil edildi",cancelled:"İptal"};
const next:Record<string,string[]>={requested:["quoted","cancelled"],quoted:["requested","cancelled"],quote_approved:["in_progress","cancelled"],in_progress:["completed","cancelled"],completed:["in_progress"],accepted:["collected"],collected:[],cancelled:[]};
const money=(c=0)=>(c/100).toLocaleString("tr-TR",{style:"currency",currency:"TRY"});
export default function Service(){
 const [data,setData]=useState<Data|null>(null),[selected,setSelected]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false),[filter,setFilter]=useState(""),[note,setNote]=useState(""),[link,setLink]=useState(""),[offline,setOffline]=useState(false);
 const [files,setFiles]=useState<{id:string;file_name:string}[]>([]);const current=data?.jobs.find(j=>j.id===selected);const [listening,setListening]=useState(false);const speech=useRef<{stop:()=>void}|null>(null);
 async function api(path:string,body?:unknown){const org=data?.organization.id||new URLSearchParams(location.search).get("organizationId")||localStorage.getItem("teksanor_organization")||"";const r=await fetch(path,{method:body?"POST":"GET",headers:{"Content-Type":"application/json","X-Organization-Id":org},body:body?JSON.stringify(body):undefined,cache:"no-store"});const d=await r.json();if(r.status===401){location.href="/giris";throw new Error("Giriş gerekli.");}if(!r.ok)throw new Error(d.error||"İşlem tamamlanamadı.");return d;}
 async function load(){try{const d=await api("/api/service/jobs") as Data;setData(d);}catch(e){setMessage(String(e));}}
 useEffect(()=>{void load();const changed=()=>setOffline(!navigator.onLine);changed();window.addEventListener("online",changed);window.addEventListener("offline",changed);return()=>{speech.current?.stop();window.removeEventListener("online",changed);window.removeEventListener("offline",changed);};},[]);
 useEffect(()=>{setNote(current?.outcome||"");setLink("");setFiles([]);if(current&&data){fetch(`/api/uploads?organizationId=${encodeURIComponent(data.organization.id)}`,{cache:"no-store"}).then(r=>r.ok?r.json():{files:[]}).then(d=>setFiles((d.files||[]).filter((f:{record_id:string})=>f.record_id===current.id))).catch(()=>setMessage("Belgeler alınamadı."));}},[selected,current?.version]);
 async function act(body:Record<string,unknown>){setBusy(true);setMessage("");try{const d=await api("/api/service/jobs",body);if(d.path)setLink(new URL(d.path,location.origin).href);else{setLink("");await load();}setMessage("İşlem kaydedildi.");return d;}catch(e){setMessage(e instanceof Error?e.message:"İşlem tamamlanamadı.");return null;}finally{setBusy(false);}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const r=await act({action:"create",...values});if(r){setCreating(false);setSelected(r.id);}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!current)return;const fields=Object.fromEntries(new FormData(e.currentTarget));await act({action:"update",id:current.id,version:current.version,outcome:note,...fields});}
 async function upload(file:File){if(!current||!data)return;setBusy(true);try{const form=new FormData();form.set("file",file);form.set("recordType","work_order");form.set("recordId",current.id);const r=await fetch("/api/uploads",{method:"POST",headers:{"X-Organization-Id":data.organization.id},body:form});const d=await r.json();if(!r.ok)throw new Error(d.error);setFiles(f=>[...f,{id:d.id,file_name:file.name}]);setMessage("Fotoğraf/belge yüklendi.");}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 function dictate(){const Constructor=(window as unknown as {SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any}).SpeechRecognition||(window as unknown as {webkitSpeechRecognition?:new()=>any}).webkitSpeechRecognition;if(!Constructor){setMessage("Bu tarayıcı sesle yazmayı desteklemiyor. Telefon klavyesinin mikrofonunu kullanabilirsiniz.");return;}const r=new Constructor();r.lang="tr-TR";r.continuous=false;r.interimResults=false;r.onresult=(event:any)=>setNote(n=>`${n}\n${event.results[0][0].transcript}`.trim());r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setMessage("Ses alınamadı. Mikrofon iznini kontrol edin.");};speech.current=r;setListening(true);r.start();}
 async function draft(){setBusy(true);try{const d=await api("/api/service/draft",{note});setNote(d.draft);setMessage(d.source==="llm"?"Taslağı kontrol edip Kaydet düğmesiyle onaylayın.":"Notunuz taslağa aktarıldı. Yapay zekâ bağlantısı etkin değil.");}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 function localDraft(restore=false){if(!current||!data)return;const key=`teksanor-draft:${data.userId}:${data.organization.id}:${current.id}`;try{if(restore){const value=localStorage.getItem(key);if(value)setNote(value);setMessage(value?"Taslak açıldı; sunucuya kaydetmek için Kaydet'e basın.":"Bu cihazda taslak yok.");}else{localStorage.setItem(key,note);setMessage("Taslak bu cihazda saklandı. Ortak cihaz kullanıyorsanız taslağı silin.");}}catch{setMessage("Cihazda taslak saklanamadı.");}}
 const assetFilter=typeof window!=="undefined"?new URLSearchParams(location.search).get("asset"):null;
 const jobs=data?.jobs.filter(j=>(!assetFilter||j.asset_id===assetFilter)&&`${j.title} ${j.customer_name} ${j.order_number}`.toLocaleLowerCase("tr-TR").includes(filter.toLocaleLowerCase("tr-TR")))||[];
 return <main className="service-shell"><header className="service-header"><div><Link href="/panel">← Şirket paneli</Link><h1>Servis masası</h1><p>{data?.organization.name||"Çalışma alanı yükleniyor"}</p></div>{data?.manage&&<button onClick={()=>setCreating(!creating)}>Yeni servis talebi</button>}</header><p className="service-message" role="status">{offline?"Çevrimdışısınız. Notunuzu cihazda taslak olarak saklayabilirsiniz. ":""}{message}</p>
 {creating&&<form className="service-card service-grid" onSubmit={create}><h2>Yeni servis talebi</h2><label>İş başlığı<input name="title" required maxLength={240}/></label><label>Müşteri<input name="customerName" maxLength={240}/></label><label>Adres / saha<input name="location" maxLength={400}/></label><label>Tarih<input name="scheduledDate" type="date"/></label><label>Ekipman<select name="assetId"><option value="">Ekipmansız kayıt</option>{data?.assets.map(a=><option key={a.id} value={a.id}>{a.asset_code} · {a.name}</option>)}</select></label><label>Sorumlu<select name="assignedUserId"><option value="">Ben</option>{data?.members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label><label className="service-wide">Talep açıklaması<textarea name="description" rows={3}/></label><button disabled={busy||offline}>Talebi aç</button></form>}
 <div className="service-workspace"><aside className="service-list"><label>Servis ara<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="İş, müşteri veya numara"/></label>{jobs.map(j=><button className={`service-item ${selected===j.id?"selected":""}`} key={j.id} onClick={()=>setSelected(j.id)}><small>{j.order_number}</small><strong>{j.title}</strong><span>{j.customer_name||"Müşteri belirtilmedi"}</span><span className="service-stage">{labels[j.stage]}</span></button>)}{data&&!jobs.length&&<p>Bu görünümde servis kaydı yok.</p>}</aside>
 {current?<section className="service-card"><div className="service-detail-heading"><div><small>{current.order_number}</small><h2>{current.title}</h2><p>{current.customer_name} · {current.location}</p></div><span className="service-stage">{labels[current.stage]}</span></div><p>{current.description}</p>{current.asset_id&&<p>{current.asset_code} · {current.asset_name} {data?.assets.some(a=>a.id===current.asset_id)&&<a href={`/api/service/qr?asset=${encodeURIComponent(current.asset_id)}&organizationId=${encodeURIComponent(data!.organization.id)}`} download>Ekipman QR etiketini indir</a>}</p>}
 <form onSubmit={save} key={current.id+":"+current.version} className="service-grid">
 {data?.manage&&<>{([['quote','Teklif toplamı (TL)'],['labor','İşçilik maliyeti (TL)'],['parts','Parça maliyeti (TL)'],['travel','Ulaşım maliyeti (TL)'],['paid','Tahsil edilen (TL)']] as const).map(([key,label])=><label key={key}>{label}<input name={key} type="number" min="0" max="100000000" step="0.01" defaultValue={Number(current[`${key}_cents` as keyof Job]||0)/100}/></label>)}<div className="service-totals"><strong>İş brüt farkı: {money(current.margin_cents)}</strong><span>Kalan tahsilat: {money(current.remaining_cents)}</span><small>Vergi ve genel giderler dahil değildir.</small></div></>}
 <label className="service-wide">Yapılan işlem / saha notu<textarea rows={6} value={note} maxLength={6000} onChange={e=>setNote(e.target.value)} readOnly={!data?.canWrite}/></label>
 {data?.canWrite&&<><div className="service-actions service-wide"><button type="button" onClick={listening?()=>speech.current?.stop():dictate}>{listening?"Dinlemeyi bitir":"Sesle yaz"}</button><button type="button" onClick={()=>void draft()} disabled={!note||busy||offline}>Rapor taslağı hazırla</button><button type="button" onClick={()=>localDraft()}>Cihazda taslak sakla</button><button type="button" onClick={()=>localDraft(true)}>Taslağı aç</button><button type="button" onClick={()=>{if(data)localStorage.removeItem(`teksanor-draft:${data.userId}:${data.organization.id}:${current.id}`);setMessage("Cihazdaki taslak silindi.");}}>Taslağı sil</button></div><small className="service-wide">Sesle yazma tarayıcınızın konuşma hizmetini kullanabilir. Cihaz taslakları kendiliğinden sunucuya gönderilmez.</small><label>Durum<select name="stage" defaultValue={current.stage}><option value={current.stage}>{labels[current.stage]}</option>{(next[current.stage]||[]).filter(n=>data?.manage||["in_progress","completed"].includes(n)).map(n=><option key={n} value={n}>{labels[n]}</option>)}</select></label><button disabled={busy||offline}>Kaydet</button></>}
 </form>
 <div className="service-actions">{data?.manage&&["quoted","completed"].includes(current.stage)&&<button disabled={busy||offline} onClick={()=>void act({action:"share",id:current.id,version:current.version,purpose:current.stage==="quoted"?"quote":"completion"})}>Müşteri onay bağlantısı oluştur</button>}<button onClick={()=>window.print()}>Servis formu / PDF</button>{data?.canWrite&&<label className="service-upload">Fotoğraf veya belge ekle<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy||offline} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value="";}}/></label>}</div>
 {link&&<div className="service-share"><p>Bu bağlantıya sahip kişi yalnızca ilgili teklifi veya iş raporunu görüp onaylayabilir. Bağlantı 7 gün geçerlidir.</p><input value={link} readOnly aria-label="Müşteri onay bağlantısı"/><button onClick={()=>navigator.clipboard.writeText(link).then(()=>setMessage("Bağlantı kopyalandı.")).catch(()=>setMessage("Bağlantıyı kutudan seçip kopyalayın."))}>Kopyala</button></div>}
 <ul>{files.map(f=><li key={f.id}><a href={`/api/uploads/${f.id}?organizationId=${encodeURIComponent(data!.organization.id)}&download=1`}>{f.file_name}</a></li>)}</ul>
 <article className="service-print"><h1>{data?.organization.name} · Servis Formu</h1><p>{current.order_number} · {current.title}</p><p>Müşteri: {current.customer_name}</p><p>Saha: {current.location}</p><p>Tarih: {current.scheduled_date||"Belirtilmedi"}</p><p>Ekipman: {current.asset_code||"Belirtilmedi"}</p><p>Teklif toplamı: {money(current.quote_cents)}</p><h2>Yapılan işlem</h2><p style={{whiteSpace:"pre-wrap"}}>{current.outcome||"Henüz kaydedilmedi."}</p><p>Durum: {labels[current.stage]}</p><small>Servis kaydıdır; mali fatura veya nitelikli elektronik imza değildir.</small></article>
 </section>:<section className="service-card service-empty"><h2>İşi baştan sona takip edin</h2><p>Talep → teklif → müşteri onayı → saha kaydı → servis formu → tahsilat.</p><p>Soldan bir servis seçin veya yeni talep açın.</p></section>}
 </div></main>;
}
